# Copyright (c) 2021 Synopsys, Inc. All rights reserved worldwide.

name: 'Synopsys Intelligent Security Scan'
description: 'Initiate optimized SAST/SCA scans based on code changes and policy with filtered results for display in GitHub.'
author: 'DevSecOps Team @ Synopsys SIG'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  ioServerUrl:
    description: 'The server Host URL for Intelligent Scan Engine eg http://localhost:1111 or https://21b7.ngrok.io'
    required: true
    default: 'http://localhost:9090'
  ioServerToken:
    description: 'The server password for Intelligent Scan Engine'
    required: false
    default: ""
  ioManifestUrl:
    description: 'HTTP URL to download IO Manifest file synopsys-io.yml'
    required: false
  workflowServerUrl:
    description: 'The server Host URL for Intelligent Scan Workflow Engine eg http://localhost:1111 or https://21b7.ngrok.io'
    required: true
    default: 'http://localhost:9091'
  workflowVersion:
    description: 'The workflow jar version to retrieve for Intelligent Scan Engine'
    required: false
    default: 2021.04
  additionalWorkflowArgs:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
  stage:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
    default: 'IO' # This is either IO or WORKFLOW 

runs:
  using: 'node12'
  main: 'index.js'
